### ISSUE TITLE
Tracking metadata enhancements

### ISSUE THREAD

**Issue by certuna** [navidrome/navidrome#1036]
This is an issue to track various metadata enhancements in Navidrome's tag scanner, database and API, and their dependencies on other parts of Navidrome. Will make it easier to see which metadata enhancements can be implemented relatively easily now, and which ones require more fundamental changes first.

** Track level metadata **

- [ ] Work `TIT1` note: used to group files together in one work. reading, storing and exposing it in the API would not be much work, but the implementation how to perform grouping in the UI is probably difficult.
- [ ] Song Title `TIT2`
- [ ] Song subtitle/description `TIT3` _note: what to do with this field in the UI? Append to Song Title? Separate field/column?_
- [ ] Movement `MVMN`,`MVIN` _note: what to do with this field in the UI? Append to Work like iTunes does, `"Work:" &  "Movement Index" & "Movement Name"`? Or separate field/column?_
- [ ] Language `TLAN`
- [ ] Key `TKEY`
- [ ] BPM `TBPM`
- [ ] Original date of the work/composition `TDOR` _note: Picard populates this field with the first-date-of-album-release instead, see below_
- [ ] Recording date `TDRC`
- [ ] First release date of this recording`TDRL` _note: Picard populates this field with the (re)issue date of the album, see below_
- [ ] Genre `TCON` _note: in order to support multiple genre tags, this needs a database schema redesign first, to accomodate the many-to-many relationship between genre-mediafile_
- [ ] Mood `TMOO` _note: in order to support multiple mood tags, this needs a database schema redesign first, to accomodate the many-to-many relationship between mood-mediafile_
- [ ] Comments `COMM` _note: we're assuming that when the comments of all tracks in an album are all identical, they are album-level comments, if they are different, the comments are mediafile-level. Might be worth considering that a file might have multiple comments fields_
- [ ] Grouping `GRP1`
- [ ] [Musicbrainz Work ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html) `TXXX`
- [ ] [Musicbrainz Recording ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html) `TXXX`
- [ ] [Musicbrainz Track ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html) `TXXX`
- [ ] [Musicbrainz Artist ID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html) `TXXX`
- [ ] [Musicbrainz AcoustID](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html) `TXXX`
- [ ] Unsynced lyrics `USLT` _note: would needs support in the upstream jinke-react-player_
- [ ] Synced lyrics `SYLT` _note: would needs support in the upstream jinke-react-player_
- [ ] Sort Song Title `TSOT`_note: Navidrome reads and stores this, but does not use it_
- [ ] Song Image `APIC`
- [ ] ReplayGain Track Gain/Peak/Range `TXXX` _note: trivial to read, store and include in the `song` API, but probably needs support in the upstream jinke-react-player_
- [ ] ReplayGain Reference Loudness `TXXX`_note: trivial to read, store and include in the `song` API, but probably needs support in the upstream jinke-react-player_

** Album level metadata **
The fields are stored in the tags per song, but apply to the album as a whole, typically they have identical values for all songs of the album
- [ ] Album Title `TALB`
- [ ] Album Artist `TPE2` _note: see artist tags section below_
- [ ] Album Sort Title `TSOA` _note: Navidrome reads and stores this, but does not use it_
- [ ] Album cover `APIC`
- [ ] Comments and Album Description `COMM` _note: we're assuming that when the comments of all tracks in an album are all identical, they are album-level comments, if they are different, the comments are mediafile-level._
- [ ] Media Type `TMED` _note: "CD/DD" for CD DDD, "TT/33" for 33 rpm LP, "ANA/8CA" for analogue 8-track cassette_
- [ ] Compilation `TCMP` _note: already supported, Navidrome assumes an album with this `TRUE` is a various artists compilation_
- [ ] Release Type `TXXX:Musicbrainz Album Type` _note: "album", "single", "live", "dj-mix", "audiobook". Comma separated!_
- [ ] Musicbrainz Release Status _note: "official", "non-official"_
- [ ] Label/Publisher _note: Navidrome reads and stores this, but does not use it_
- [ ] Catalog Number _note: Navidrome reads and stores this, but does not use it_
- [ ] Album country `TXXX:MusicBrainz Album Release Country`
- [ ] ISRC/UPC code `TSRC`
- [ ] Album (re)issue date `TDRL` _note: there's no official field for this, however Picard tags `TDRL` with one album level (re)issue date instead of individual song dates. Navidrome currently rolls up track-level TDRL dates to album level, so "2015" when all dates are the same, and "1995-2015" when there's a range of individual dates_
- [ ] Album original release date `TDOR` _note: this is not what `TDOR` was supposed to be used for, however Picard tags this field with one album level original release date instead of individual song dates. _
- [ ] Musicbrainz Release ID
- [ ] Musicbrainz Release Group ID
- [ ] Musicbrainz Original Release ID
- [ ] Musicbrainz Album Artist ID _note: see artist tags section below_
- [ ] ReplayGain Album Gain/Peak/Range `TXXX` _note: trivial to read, store and include in the `song` API, but probably needs support in the upstream jinke-react-player_
- [ ] various calculated fields: total time, playcount, etc

**Disc level metadata**
This is a sub-grouping of tracks below the album.
- [ ] Disc Number `TPOS` _note: hidden from the web UI when an album has only one disc_
- [ ] Disc Subtitle `TSST` _note: hidden from the web UI when an album has only one disc_

**Artist-type metadata**

Supporting multiple artists and additional credits (composer, remixer, producer etc) requires fundamental changes to the Database schema to accommodate the complex many-to-many relationships artist-role-album-mediafile. Most of this info cannot be exposed over the Subsonic API, since its specs only define one artist, one album artist, and no other roles/credits.

Fields:
- [ ] multi-valued fields: performing artist (`TPE1` and `TXXX:Artists`) and album artist (`TPE2`, `TXXX:Album Artists`)
- [ ] roles/credits: conductor (`TPE3`), remixer `TPE4`, original artist `TOPE`, composer `TCOM`, lyricist `TEXT`, musician credits (guitar, vocals) `TMCL` and "involved people" (producer, engineer, dj-mixer) `TIPL`
- [ ] Sort Artist `TSOP`, Sort Album Artist `TSO2`, Sort Composer `TSOC` _note: while this field is helpful to sort "The Beatles" under B, this field also has values like "Dylan, Bob" to sort him under D, which is something that a lot of people dislike._
- [ ] Artist Image `APIC` _note: can be an embedded tag, but also external from last.fm, Spotify, MusicBrainz, Allmusic, Wikipedia, etc_
- [ ] Artist biography _note: can in theory be an embedded tag with `COMM`, but I've never seen this in the wild. Usually this comes from last.fm, Spotify, MusicBrainz, Allmusic, Wikipedia, etc_
- [ ] Artist country _note: could in theory be an embedded tag with `TXXX:Artist Country` or something, but I've never seen this in the wild. Usually this comes from last.fm, Spotify, MusicBrainz, Allmusic, Wikipedia, etc_
- [ ] various calculated fields: artist date range, total number of tracks, total time, total playcount, etc.

**Comment by deluan** [comment]
@certuna: Navidrome don't read the `TLEN`, but it provides this information. Both `ffmpeg` and `taglib` extractors provide this info. Is there any advantage of reading the tag versus relying on the info provided by the extractors?

**Comment by certuna** [comment]
> @certuna: Navidrome don't read the `TLEN`, but it provides this information. Both `ffmpeg` and `taglib` extractors provide this info. Is there any advantage of reading the tag versus relying on the info provided by the extractors?

Yeah I think this is indeed best handled upstream by the tag library.

**Comment by adamdmoss** [comment]
Is metadata in .dsf supposed to extract/scan intact at this point?  Because I don't believe it's working; should I file a separate issue?

**Comment by certuna** [comment]
Correct, DSF at this point can only be read by ffmpeg, not by Taglib. Not much we can do about that...

**Comment by adamdmoss** [comment]
ffmpeg scanner did indeed fix it - apologies for the noise.

**Comment by SenorSmartyPants** [comment]
Please display 'MusicBrainz Album Comment' field if present in ID3 tags. Beets adds this to metadata if release has it set.

https://musicbrainz.org/release/c28de232-bb53-4ccc-aa29-60ca5decbbad

As displayed in Picard.
![image](https://user-images.githubusercontent.com/991618/139933966-73a8f679-c748-4769-90d1-c93d9b7224b0.png)

**Comment by rombat** [comment]
any plan to handle the `Arranger`  tag for tracks ? That would be great too !

**Comment by metalheim** [comment]
@certuna navidrome reads and uses replaygain. Can you please update the first Post here ?

**Comment by deluan** [comment]
> Please display 'MusicBrainz Album Comment' field if present in ID3 tags. Beets adds this to metadata if release has it set.
> 
> https://musicbrainz.org/release/c28de232-bb53-4ccc-aa29-60ca5decbbad
> 
> As displayed in Picard. ![image](https://user-images.githubusercontent.com/991618/139933966-73a8f679-c748-4769-90d1-c93d9b7224b0.png)

Hey @SenorSmartyPants, what is the difference between this tag and [_releasecomment](https://github.com/navidrome/navidrome/issues/1976#issuecomment-1305314286)? 

By the way, do you need to configure anything in Picard for it to import this tag? My Picard (with default settings) can't seem to import it. Maybe it is a Beets thing?

![Screenshot 2023-12-27 at 4 37 59 PM](https://github.com/navidrome/navidrome/assets/331353/21a4ea63-1976-42c6-8d2a-373993c77f9b)

**Comment by SenorSmartyPants** [comment]
I think they are the same (I am by no means an expert). I followed that link and this one from there https://community.metabrainz.org/t/add-album-version-tag-using-picard/539876 and came up with this Picard script.

`$set(MusicBrainz Album Comment,%_releasecomment%)`

Yes, by default it seems that Picard does not tag this field and beets does. It appears that I have the correct field name as Picard matches the one it makes with the beets tag one. But I could always send you an mp3 with the field in it, or ffmpeg dump of one.

**Comment by deluan** [comment]
> `$set(MusicBrainz Album Comment,%_releasecomment%)`

Ah yes, `_releasecomment`. This is already imported (as [`MusicBrainz Album Comment`](https://github.com/navidrome/navidrome/blob/814161d78db0dc07c16fa6e80f6ff1710866e31b/scanner/metadata/metadata.go#L207)) but not used anywhere ATM. In a future release, we will allow it to be used as disambiguation.

**Comment by michaelkrieger** [comment]
A non-numeric **disc number** doesn't seem to be honoured by Navidrome's web interface, merging all discs into one.
An example of this is a mix released by a popular TV show.  It had a "TV Version" and a "Blog Version" of the same CD album.

Yes, this could be referenced as "Disc Subtitle", but there is no disc number in this case.
Yes, this could be named differently in the albums, but i do want to keep these together as one album.

Should Navidrome's web interface simply be squashing a disc number of "BLOG" or "TV" or "RED"/"GREEN" into a flat no-disc album?  Probably not.

If the desire is to keep this field numeric for player compatibility purposes, maybe giving the discs a(n arbitrary) number and moving the text to the subtitle field internally?

Note: This would also impact vinyl numbering like A1, A2, B1, B2, C1, C2.

Note: Differs from #1652 and #2104 as this is disc number and not track number

**Comment by matt77hias** [comment]
>GRP1 Grouping it has never become quite clear whether this field is meant to work on the album level, song level or other, as Apple never specified how it should be used. This field was never defined in the id3v2 specs, and Vorbis doesn't have specs, however people seem to use it as a freeform tag field https://github.com/navidrome/navidrome/issues/2045

It would be nice if the `grouping` (`GRP1` (MP3) / `©grp` (MP4)) tag could be used as a "sub-header" within an album similar to the `set subtitle`, but not for all tracks of a single disc but rather a subset of tracks on the same disk:

Examples:
* `Original Album`, `Remixes`, `Demos`, `Bonus`, `Hidden`, etc.
* `Act I`, `Act II`, etc.
* https://getmusicbee.com/forum/index.php?topic=11990.0

_Movements could be used too, but those are more tailored towards classical music only. Furthermore, there are actually three closely related tags: `movement`, `movement total`, `movement number`._

References:
* Mp3Tag: https://docs.mp3tag.de/mapping-table/
* MusicBee: https://getmusicbee.com/forum/index.php?topic=39759.msg214907#msg214907

>TMED Media Type: source of the audio, values are for example "CD/DD" for DDD audio CD, "TT/33" for 33rpm LP, "ANA/8CA" for analogue 8-track cassette note: in principle this could be song-level info, but in practice this is nearly always an album-level field since it's rare that individual songs on an album come from different sources

It would be nice if the media type could be used to group the albums of the same artist. That way it would be possible to have CD, Vinyl, Cassette, etc. subsections. Or a more liberal use: Studio, EP, Single, Compilation, Live, etc. subsections.

**Comment by JannetGen** [comment]
+1 for better metadata support. A lot of these tags are already being maintained by users in tools like MusicBrainz Picard, so exposing them in Navidrome would make libraries much richer without extra work on the user's side.
I've also found that cleaning up tags beforehand makes a huge difference. For quick checks and edits I've occasionally used [editmp3tags.com](https://editmp3tags.com/) to fix inconsistent metadata before rescanning. It helps avoid some of the library organization issues that come from messy tags in the first place.

Really like having all these metadata enhancements tracked in one place.

**Comment by fooness** [comment]
Question: After an initial scan, Navidrome stores persistent identifiers for artists, albums, and tracks (effectively files), hence externally editing/fixing/updating metadata of your files does not change/fix anything in the Navidrome library that was already added; and new scans would produce duplicates? (At least that’s what I’m experiencing, and it’s definitely not *convenient* to be deleting the Navidrome database and starting all over again after externally changing metadata.)
