### ISSUE TITLE
[Bug]: URL's in meta elements go to localhost instead of domain on the share player.

### ISSUE THREAD

**Issue by ahdplayer** [navidrome/navidrome#2552]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.49.3

### Current Behavior

When I play a shared song and look at the HTML elements I see that the meta tags that have URL's in them go to 127.0.0.1
even though there's a reverse proxy setup that works on everything else. Heres an example : 

`<meta property="og:url" content="https://127.0.0.1:8080/share/RI0mJ381hh">`

`<meta property="og:image" content="https://127.0.0.1:8080/share/img/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFsLTUyNzNjYzUwZWRjYWIzYzEwYzhiYTNkMWJhZTRmMDNjXzAiLCJpc3MiOiJORCJ9.CUrgxfmdFBlVl_5Tr3Cbks3zEDqX08KvEV2fvpRVtAQ?size=300">`

### Expected Behavior

the meta tags should point to the domain instead of localhost.

### Steps To Reproduce

0. setup navidrome to work behind nginx
1. share a song
2. open the shared song from the shared link
3. open developer tools to see page source code
4. look at meta tags that contain URL's
5. you will see that they point to 127.0.0.1:port/share instead of subdomain.domain.com/share

### Environment

```markdown
- OS: Arch Linux 6.5.3-arch1-1
- Browser: Firefox 117.0.1 on Arch Linux
- Client: Integrated web server
```

### How Navidrome is installed?

Package

### Configuration

```toml
MusicFolder = "/home/username/navidrome/musics"
Port = 8080
UIWelcomeMessage = "Welcome"
EnableSharing = "true"
DefaultTheme = "Spotify-ish"
DefaultLanguage = "tr"
```

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by metalheim** [comment]
Cannot confirm this. With my instance running current version 0.50.2, the Meta properties ```og:image``` and ```og:url``` use the correct domain that the server ist hosted under.

Maybe this was already fixed and not mentioned? Or something else wrong with your setup?

**Comment by deluan** [comment]
Maybe Navidrome is not being able to get the correct public address of your server? You can try to set the full server address in the BaseURL config option: https://www.navidrome.org/docs/usage/configuration-options/#:~:text=(all%20IPs)-,BaseUrl,-ND_BASEURL

Let me know if this is still an issue, or if the suggestion above fixes it.
