### ISSUE TITLE
Tracking OpenSubsonic extensions

### ISSUE THREAD

**Issue by deluan** [navidrome/navidrome#2695]
This is a place to track all implemented OS extensions, while it is not added to the [documentation](https://www.navidrome.org/docs/developers/subsonic-api/). The list below reflects what is available in the develop build/image, not necessarily in the latest release

### [Child](https://opensubsonic.netlify.app/docs/responses/child/)
- [x] played
- [x] bpm
- [x] comment
- [x] sortName
- [x] mediaType
- [x] musicBrainzId
- [x] genres
- [ ] artists
- [ ] displayArtist
- [ ] albumArtists
- [ ] displayAlbumArtist
- [ ] contributors
- [ ] displayComposer
- [ ] moods
- [x] replayGain

### [AlbumID3](https://opensubsonic.netlify.app/docs/responses/albumid3/)
- [x] played
- [x] userRating
- [ ] recordLabels
- [x] musicBrainzId
- [x] genres
- [ ] artists
- [ ] displayArtist
- [ ] releaseType
- [ ] moods
- [x] sortName
- [ ] originalReleaseDate
- [x] isCompilation
- [x] discTitles #2694 

### [ArtistID3](https://opensubsonic.netlify.app/docs/responses/artistid3/)
- [x] musicBrainzId
- [x] sortName
- [ ] roles

## Extensions
- [x] [getOpenSubsonicExtensions](https://opensubsonic.netlify.app/docs/endpoints/getopensubsonicextensions/)
- [x] stream ([clarification](https://opensubsonic.netlify.app/docs/endpoints/stream/#:~:text=OpenSubsonic-,OpenSubsonic,-servers%20must%20not))
- [x] search3 ([clarification](https://opensubsonic.netlify.app/docs/endpoints/search3/#:~:text=See%20getMusicFolders.-,OpenSubsonic,-Servers%20must%20support))
- [x] [transcodeOffset](https://opensubsonic.netlify.app/docs/extensions/transcodeoffset/): 812dc2090f20ac4f8ac271b6ed95be5889d1a3ca
- [x] [formPost](https://opensubsonic.netlify.app/docs/extensions/formpost/): #2676 
- [ ] [songLyrics](https://github.com/opensubsonic/open-subsonic-api/discussions/60): #2656

**Comment by TanqBQZ** [comment]
@deluan I'm gonna advocate for the implementation of displayArtist / displayAlbumArtist

- Hide artists :
It can be used like this : 
ARTISTS : DROELOE
ARTISTS : Slippy
DISPLAYARTIST : DROELOE
TITLE : Virtual Friends (Slippy Remix)

So you can have the remixer or featured artist in artists (so the song appears on their page) but not displayed twice (in the artist section and in the title)

- Edge cases : 
It can be useful when the artists and the way they are presented on a song are different
ex:
ARTISTS : LTN
ARTISTS : Ghostbeat
DISPLAYARTIST : LTN pres. Ghostbeat

   or for a mashup:
ARTISTS : Lorde
ARTISTS : DJ Snake
ARTISTS : Lil Jon
DISPLAYARTIST : Lorde x DJ Snake & Lil Jon
TITLE : Tennis Court (Flume Remix) x Turn Down for What

It is a very useful tag for those who want to avoid duplicates in Titles and Artists tags, and to deal with specific scenarios

**Comment by deluan** [comment]
Thanks for the feedback, but I think what you are referring to is the ARTIST (singular) tag, as there is no DISPLAYARTIST tag in id3v2 and it is not a standard Vorbis comment, AFAIK.

Also, this list is not for tags, they are attributes returned by Subsonic endpoints, they don't always correspond 1x1 to tags (at least in Navidrome)

But don't worry: With #2709, if you tag your files like your examples, but use ARTIST (singular) instead of DISPLAYARTIST, it will behave exactly like you are describing it :)

**Comment by raudraido** [comment]
what about apiKeyAuthentication?

**Comment by dreamAviator** [comment]
okay so api key authentication is not yet added?

**Comment by deluan** [comment]
No, not yet, as you can see from the list above.
