### ISSUE TITLE
[Bug]: meta data is garbled text

### ISSUE THREAD

**Issue by owendswang** [navidrome/navidrome#3243]
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.52.5 (c5560888)

### Current Behavior

meta data extracted from media files is garbled text.

### Expected Behavior

normal meta data text.

### Steps To Reproduce

1. scan
2. meta data is garbled text

### Environment

```markdown
- OS:Ubuntu 24.04 arm64
- Browser: Firefox
- Client: 115.15.0esr (64-bit)
```

### How Navidrome is installed?

Docker

### Configuration

```toml
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/mnt/navidrome/data:/data"
      - "/mnt/Music:/music:ro"
```

### Relevant log output

```shell
time="2024-08-20T15:19:23Z" level=info msg="goose: no migrations to run. current version: 20240511210036\n"

time="2024-08-20T15:19:23Z" level=info msg="Starting signaler"

time="2024-08-20T15:19:23Z" level=info msg="Setting Session Timeout" value=24h

time="2024-08-20T15:19:23Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=2

time="2024-08-20T15:19:23Z" level=error msg="Agent not available. Check configuration" name=lastfm

time="2024-08-20T15:19:23Z" level=error msg="Agent not available. Check configuration" name=spotify

time="2024-08-20T15:19:23Z" level=info msg="Creating Image cache" maxSize="100 MB" path=/data/cache/images

time="2024-08-20T15:19:23Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music

time="2024-08-20T15:19:23Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg

time="2024-08-20T15:19:23Z" level=info msg="Spotify integration is not enabled: missing ID/Secret"

time="2024-08-20T15:19:25Z" level=error msg="Agent not available. Check configuration" name=lastfm

time="2024-08-20T15:19:25Z" level=error msg="Agent not available. Check configuration" name=spotify

time="2024-08-20T15:19:25Z" level=info msg="Scheduling periodic scan" schedule="@every 1h"

time="2024-08-20T15:19:25Z" level=info msg="Starting scheduler"

time="2024-08-20T15:19:25Z" level=info msg="Mounting Native API routes" path=/api

time="2024-08-20T15:19:25Z" level=error msg="Agent not available. Check configuration" name=lastfm

time="2024-08-20T15:19:25Z" level=error msg="Agent not available. Check configuration" name=spotify

time="2024-08-20T15:19:25Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding

time="2024-08-20T15:19:25Z" level=info msg="Mounting Subsonic API routes" path=/rest

time="2024-08-20T15:19:25Z" level=error msg="Agent not available. Check configuration" name=lastfm

time="2024-08-20T15:19:25Z" level=error msg="Agent not available. Check configuration" name=spotify

time="2024-08-20T15:19:25Z" level=info msg="Mounting Public Endpoints routes" path=/share

time="2024-08-20T15:19:25Z" level=info msg="Mounting LastFM Auth routes" path=/api/lastfm

time="2024-08-20T15:19:25Z" level=info msg="Mounting ListenBrainz Auth routes" path=/api/listenbrainz

time="2024-08-20T15:19:25Z" level=info msg="Mounting Background images routes" path=/backgrounds

time="2024-08-20T15:19:25Z" level=info msg="Mounting WebUI routes" path=/app

time="2024-08-20T15:19:25Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime=4.5ms maxSize=100MB

time="2024-08-20T15:19:25Z" level=info msg="----> Navidrome server is ready!" address="0.0.0.0:4533" startupTime=2.72s tlsEnabled=false

time="2024-08-20T15:19:27Z" level=info msg="Finished initializing cache" cache=Image elapsedTime=4.21s maxSize=100MB

time="2024-09-08T11:01:33Z" level=warning msg="HTTP: GET http://localhost:24533/api/playlist?_end=0&_sort=name&_start=-100" elapsedTime="114.981µs" httpStatus=401 remoteAddr="172.21.0.1:47198" requestId=7577328a4fd9/299dOdyRh8-054282 responseSize=29

time="2024-09-08T11:01:33Z" level=warning msg="HTTP: GET http://localhost:24533/api/transcoding?_end=1000&_order=ASC&_sort=name&_start=0" elapsedTime="59.684µs" httpStatus=401 remoteAddr="172.21.0.1:47170" requestId=7577328a4fd9/299dOdyRh8-054283 responseSize=29

time="2024-09-08T11:01:33Z" level=warning msg="HTTP: GET http://localhost:24533/api/album?_end=36&_order=DESC&_sort=recently_added&_start=0" elapsedTime="49.722µs" httpStatus=401 remoteAddr="172.21.0.1:47194" requestId=7577328a4fd9/299dOdyRh8-054284 responseSize=29
```

### Anything else?

As far as I know, ffmpeg reads metadata only in UTF-8. But some of my media files' metadata is in other character sets like GB2312.
So is there any other way to read it correctly.
Those metadata could be read correctly by Foobar2000.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

**Comment by LennertVA** [comment]
When do you get garbled text? On files with unicode metadata? Or GB2312 (why on earth...)? Both? Did you narrow it down to a specific character set?

If you have any example file that you can legally share, I suppose that would help.

**Comment by deluan** [comment]
> If you have any example file that you can legally share, I suppose that would help.

Yes, please. Also, keep in mind that by default Navidrome uses TagLib to read metadata. It only uses ffmpeg if you change the config option [Scanner.Extractor](https://www.navidrome.org/docs/usage/configuration-options/#:~:text=Empty-,Scanner.Extractor,-*).

**Comment by owendswang** [comment]
I don't know what character set they are. But here's an example file. 
[example.zip](https://github.com/user-attachments/files/16942432/example.zip)
@LennertVA @deluan

**Comment by LennertVA** [comment]
> I don't know what character set they are. But here's an example file. [example.zip](https://github.com/user-attachments/files/16942432/example.zip) @LennertVA @deluan

Well, upon looking at the file, it's not navidrome that displays the meta data as garbled text. 

The metadata in the file **is** garbled. 

`$ eyeD3 example.mp3 
ID3 v2.3:
title: ÒþÐÎ¼ÍÄî£¨µçÓ°º£½ÇÆßºÅÖÐÐ¢½é¸÷
artist: ²Ì´¾¼Ñ
album: »Øµ½×î³õ
album artist: 蔡淳佳`

`$ id3v2 -l example.mp3 
id3v1 tag info for example.mp3:
Title  : ���μ����Ӱ�����ߺ���Т���  Artist: �̴���                        
Album  : �ص����                        Year: 2009, Genre: Other (12)
Comment: www.91ting.com                  Track: 2
id3v2 tag info for example.mp3:
TIT2 (Title/songname/content description): ÒþÐÎ¼ÍÄî£¨µçÓ°º£½ÇÆßºÅÖÐÐ¢½é¸÷
TALB (Album/Movie/Show title): »Øµ½×î³õ
TRCK (Track number/Position in set): 2
APIC (Attached picture): ()[, 3]: image/jpeg, 10857 bytes
TCON (Content type): Other (12)
TYER (Year): 2009
TPE2 (Band/orchestra/accompaniment): 蔡淳佳
TPE1 (Lead performer(s)/Soloist(s)): ²Ì´¾¼Ñ
COMM (Comments): ()[chi]: www.91ting.com
`

`$ ffprobe example.mp3 
Input #0, mp3, from 'example.mp3':
  Metadata:
    title           : ÒþÐÎ¼ÍÄî£¨µçÓ°º£½ÇÆßºÅÖÐÐ¢½é¸÷
    album           : »Øµ½×î³õ
    track           : 2
    genre           : Other
    comment         : www.91ting.com
    album_artist    : 蔡淳佳
    artist          : ²Ì´¾¼Ñ
    date            : 2009
    id3v2_priv.WM/MediaClassSecondaryID: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
    id3v2_priv.WM/MediaClassPrimaryID: \xbc}`\xd1#\xe3\xe2K\x86\xa1H\xa4*(D\x1e
    id3v2_priv.WM/Provider: C\x00D\x00J\x00o\x00u\x00r\x00n\x00a\x00l\x00 \x00C\x00h\x00i\x00n\x00a\x00\x00\x00
    id3v2_priv.WM/WMContentID:  U\xde\xee;\xf9\xa9K\x9a/\x8e\xbf\x0c:&\x7f
    id3v2_priv.WM/WMCollectionID: /\xa0\xac\xc2\x92\xa0\xdcJ\x93\xd7\x82;\xca,\xd26
    id3v2_priv.WM/WMCollectionGroupID: /\xa0\xac\xc2\x92\xa0\xdcJ\x93\xd7\x82;\xca,\xd26
    id3v2_priv.WM/UniqueFileIdentifier: ;\x00\x00\x00
`

Oddly enough, the one tag that does get shown properly is the Album Artist with 蔡淳佳 which is in unicode. 

Did those other meta tags get written in some obscure unspecified charset but inserted as if they were unicode? If you know what it all should be, sounds like rewriting them properly is the way to go.

**Comment by LennertVA** [comment]
> It's read correctly by Foobar2000.

I'm not sure what to tell you - I tested with three different tools, and all three confirm that it's garbage text. Perhaps Foobar2000 is smart enough to detect that something is badly written and attempts different charsets until it comes across one that looks acceptable - but this looks like a tool compensating for bad data, and compensating for bad data is not something that an app should be doing. Navidrome doesn't at least, obviously. :)

**Comment by owendswang** [comment]
@LennertVA Thank you. But do you know what tools can I use to fix this encoding problem of a lot of media files in one time?

**Comment by LennertVA** [comment]
> @LennertVA Thank you. But do you know what tools can I use to fix this encoding problem of a lot of media files in one time?

Not offhand, no. I would be inclined to write a bash script to go over everything and write it with eyeD3, but that's assuming you can find out how to get the "real" text from the garbage.

**Comment by owendswang** [comment]
Thanks for the hint "eyeD3". I'll look into it by myself.

**Comment by owendswang** [comment]
I used pypi package "mutagen" (mid3iconv) to convert the charset from GBK and it worked.

```
# mid3iconv
Usage: mid3iconv [OPTION] [FILE]...

Mutagen-based replacement the id3iconv utility, which converts ID3 tags from
legacy encodings to Unicode and stores them using the ID3v2 format.

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -e ENCODING, --encoding=ENCODING
                        Specify original tag encoding (default is UTF-8)
  -p, --dry-run         Do not actually modify files
  --force-v1            Use an ID3v1 tag even if an ID3v2 tag is present
  --remove-v1           Remove v1 tag after processing the files
  -q, --quiet           Only output errors
  -d, --debug           Output updated tags

Files are updated in-place, so use --dry-run first.
```
